[package]
name = "bottled_discord"
version = "0.1.0"
authors = ["Thomas-QM <thomas@engineeringvirtue.net>"]

[dependencies]
typemap = "0.3.0"
serenity = "0.5.9"
json = "0.11.13"
r2d2 = "0.8.2"
time = "0.1"
chrono = "0.4"
uuid = "0.6.5"
diesel = { version = "1.0.0", features = ["postgres", "chrono", "r2d2", "uuid"] }
dotenv = "0.13.0"
rustc-serialize = "*"
nickel = "0.10.1"
oauth2 = "1.3.0"